name: 'main'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cicd:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }} 
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Build
        run: cargo build

      - name: Run unit-tests
        run: cargo test

