name: 'main'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cicd:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }} 
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4

      - name: 'Configure build'
        run: cmake -Bbuild

      - name: 'Build'
        run: cmake --build build --target all -j8

      - name: 'Run tests'
        run: ./build/src/unittests
